# Generated by Django 4.2.5 on 2024-01-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_otp_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_shope',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
