# Generated by Django 4.2.5 on 2024-01-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('  در انتظار ارسال ', '  در انتظار ارسال '), ('  ارسال شده', '  ارسال شده'), (' ارسال نشده', ' ارسال نشده')], default='در انتظار ارسال ', max_length=100),
        ),
    ]
