# Generated by Django 4.2.5 on 2024-01-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1 ', '  در انتظار ارسال '), ('2', '  ارسال شده'), (' 3', ' ارسال نشده')], default='1', max_length=100),
        ),
    ]
