# Generated by Django 4.2.5 on 2023-12-19 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tickets.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=tickets.models.generate_unic_code, max_length=6, null=True, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('priority', models.CharField(choices=[('1', ' زیاد'), ('2', 'متوسط '), ('3', 'کم ')], max_length=100)),
                ('status', models.CharField(choices=[('1', ' پاسغ داده شده'), ('2', 'پاسخ داده نشده'), ('3', '  در حال برسی')], default='3', max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('file', models.FileField(blank=True, upload_to='')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.tickets')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
