# Generated by Django 4.2.5 on 2024-01-21 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='product',
        ),
        migrations.AddField(
            model_name='products',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.seller'),
        ),
    ]
