# Generated by Django 4.2.5 on 2024-01-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='percent',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
