# Generated by Django 4.2.5 on 2024-01-21 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_seller_product_products_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='seller',
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
